name: Build and push

on:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Build container image
        run: |
          nix build
          skopeo copy --dest-creds="${{ env.REGISTRY_USER }}:${{ env.REGISTRY_PASSWORD }}" docker-archive:result "docker://${{ env.IMAGE_REGISTRY }}/pure-fpd-anon:latest"

